cluster.name: nicc
node.name: "elasticsearch02"
node.master: true
node.data: true
network:
  host : 192.168.0.11
http:
  port: 9200
discovery.zen.ping.unicast.hosts: ["192.168.0.10", "192.168.0.11", "192.168.0.12"]
discovery.zen.minimum_master_nodes: 2
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: true
xpack.security.enabled: false
xpack.watcher.enabled: false