server.host: 0.0.0.0
elasticsearch.url: http://192.168.0.13:9200
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: true
xpack.reporting.enabled: false
xpack.security.enabled: false

