path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d
config.reload.automatic: true
config.reload.interval: 3
path.logs: /var/log/logstash/conf
xpack.monitoring.elasticsearch.url: ["192.168.0.14:9200"] 
